// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	simple "github.com/joshvanl/k8s-simple-api/pkg/apis/simple"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Message_To_simple_Message,
		Convert_simple_Message_To_v1alpha1_Message,
		Convert_v1alpha1_MessageList_To_simple_MessageList,
		Convert_simple_MessageList_To_v1alpha1_MessageList,
		Convert_v1alpha1_MessageSpec_To_simple_MessageSpec,
		Convert_simple_MessageSpec_To_v1alpha1_MessageSpec,
		Convert_v1alpha1_MessageStatus_To_simple_MessageStatus,
		Convert_simple_MessageStatus_To_v1alpha1_MessageStatus,
	)
}

func autoConvert_v1alpha1_Message_To_simple_Message(in *Message, out *simple.Message, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MessageSpec_To_simple_MessageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MessageStatus_To_simple_MessageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Message_To_simple_Message is an autogenerated conversion function.
func Convert_v1alpha1_Message_To_simple_Message(in *Message, out *simple.Message, s conversion.Scope) error {
	return autoConvert_v1alpha1_Message_To_simple_Message(in, out, s)
}

func autoConvert_simple_Message_To_v1alpha1_Message(in *simple.Message, out *Message, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_simple_MessageSpec_To_v1alpha1_MessageSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_simple_MessageStatus_To_v1alpha1_MessageStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_simple_Message_To_v1alpha1_Message is an autogenerated conversion function.
func Convert_simple_Message_To_v1alpha1_Message(in *simple.Message, out *Message, s conversion.Scope) error {
	return autoConvert_simple_Message_To_v1alpha1_Message(in, out, s)
}

func autoConvert_v1alpha1_MessageList_To_simple_MessageList(in *MessageList, out *simple.MessageList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Items = *(*[]simple.Message)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MessageList_To_simple_MessageList is an autogenerated conversion function.
func Convert_v1alpha1_MessageList_To_simple_MessageList(in *MessageList, out *simple.MessageList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MessageList_To_simple_MessageList(in, out, s)
}

func autoConvert_simple_MessageList_To_v1alpha1_MessageList(in *simple.MessageList, out *MessageList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if in.Items == nil {
		out.Items = make([]Message, 0)
	} else {
		out.Items = *(*[]Message)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_simple_MessageList_To_v1alpha1_MessageList is an autogenerated conversion function.
func Convert_simple_MessageList_To_v1alpha1_MessageList(in *simple.MessageList, out *MessageList, s conversion.Scope) error {
	return autoConvert_simple_MessageList_To_v1alpha1_MessageList(in, out, s)
}

func autoConvert_v1alpha1_MessageSpec_To_simple_MessageSpec(in *MessageSpec, out *simple.MessageSpec, s conversion.Scope) error {
	out.Header = in.Header
	out.Body = in.Body
	return nil
}

// Convert_v1alpha1_MessageSpec_To_simple_MessageSpec is an autogenerated conversion function.
func Convert_v1alpha1_MessageSpec_To_simple_MessageSpec(in *MessageSpec, out *simple.MessageSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MessageSpec_To_simple_MessageSpec(in, out, s)
}

func autoConvert_simple_MessageSpec_To_v1alpha1_MessageSpec(in *simple.MessageSpec, out *MessageSpec, s conversion.Scope) error {
	out.Header = in.Header
	out.Body = in.Body
	return nil
}

// Convert_simple_MessageSpec_To_v1alpha1_MessageSpec is an autogenerated conversion function.
func Convert_simple_MessageSpec_To_v1alpha1_MessageSpec(in *simple.MessageSpec, out *MessageSpec, s conversion.Scope) error {
	return autoConvert_simple_MessageSpec_To_v1alpha1_MessageSpec(in, out, s)
}

func autoConvert_v1alpha1_MessageStatus_To_simple_MessageStatus(in *MessageStatus, out *simple.MessageStatus, s conversion.Scope) error {
	out.Sent = in.Sent
	return nil
}

// Convert_v1alpha1_MessageStatus_To_simple_MessageStatus is an autogenerated conversion function.
func Convert_v1alpha1_MessageStatus_To_simple_MessageStatus(in *MessageStatus, out *simple.MessageStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MessageStatus_To_simple_MessageStatus(in, out, s)
}

func autoConvert_simple_MessageStatus_To_v1alpha1_MessageStatus(in *simple.MessageStatus, out *MessageStatus, s conversion.Scope) error {
	out.Sent = in.Sent
	return nil
}

// Convert_simple_MessageStatus_To_v1alpha1_MessageStatus is an autogenerated conversion function.
func Convert_simple_MessageStatus_To_v1alpha1_MessageStatus(in *simple.MessageStatus, out *MessageStatus, s conversion.Scope) error {
	return autoConvert_simple_MessageStatus_To_v1alpha1_MessageStatus(in, out, s)
}
